apiVersion: v1
kind: Service
metadata:
  name: dvlp-app
  labels:
    app: dvlp-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: dvlp-app
