apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dvlp-app
spec:
  selector:
    matchLabels:
      app: dvlp-app
  template:
    metadata:
      labels:
        app: dvlp-app
    spec:
      containers:
      - name: kim_vid
        image: dockindaddy10291995/kim_vid:Tage
        command: ["npm", "start"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "64Mi"
            cpu: "70m"
          limits:
            memory: "64Mi"
            cpu: "70m"
